import type { CalendarEvent } from "./types";

export const events: CalendarEvent[] = [
  {
    id: "c-01",
    title: "Совет директоров",
    kind: "совещание",
    date: "2026-04-23",
    time: "10:00",
    location: "Центральный офис, зал «Алтай»",
    participants: 9,
  },
  {
    id: "c-02",
    title: "Презентация клиенту: АО «КазМунайГаз»",
    kind: "встреча с клиентом",
    date: "2026-04-24",
    time: "15:00",
    location: "Онлайн",
    participants: 6,
  },
  {
    id: "c-03",
    title: "Релиз Halyk Cloud 2.4",
    kind: "релиз",
    date: "2026-04-25",
    location: "Продакшн",
  },
  {
    id: "c-04",
    title: "Общее собрание: итоги квартала",
    kind: "корпоратив",
    date: "2026-04-28",
    time: "17:00",
    location: "ЦОД «Алматы-2», атриум",
    participants: 180,
  },
  {
    id: "c-05",
    title: "Внутренний аудит ISO 27001",
    kind: "дедлайн",
    date: "2026-04-30",
  },
  {
    id: "c-06",
    title: "Обучение: SOC playbook v3",
    kind: "обучение",
    date: "2026-05-05",
    time: "11:00",
    participants: 42,
  },
  {
    id: "c-07",
    title: "Выезд в Астану: встреча с регулятором",
    kind: "встреча с клиентом",
    date: "2026-05-08",
    time: "09:30",
    location: "Астана",
    participants: 4,
  },
  {
    id: "c-08",
    title: "Корпоратив ко Дню связиста",
    kind: "корпоратив",
    date: "2026-05-17",
    time: "19:00",
    location: "The Ritz-Carlton, Алматы",
    participants: 320,
  },
];
