import type { Employee } from "./types";

export const CURRENT_USER = {
  id: "u-ceo",
  fullName: "Айдын Сагинтаев",
  position: "Председатель правления",
  department: "Правление",
  avatarTone: "#007A5C",
};

export const employees: Employee[] = [
  {
    id: "e-001",
    fullName: "Жанар Ахметова",
    position: "Директор по эксплуатации",
    department: "Эксплуатация",
    city: "Алматы",
    email: "j.akhmetova@halyk-kazteleport.kz",
    phone: "+7 (727) 244-11-02",
    tgUsername: "j_akhmetova",
    startedAt: "2018-03-12",
    manager: "Айдын Сагинтаев",
    skills: ["SLA", "NOC", "ITIL", "ЦОД Tier III"],
    bio: "Отвечает за бесперебойную работу инфраструктуры и дата-центров. 14 лет в телекоме.",
    avatarTone: "#007A5C",
  },
  {
    id: "e-002",
    fullName: "Рустем Жакупов",
    position: "Руководитель ЦОД Алматы-1",
    department: "ЦОД",
    city: "Алматы",
    email: "r.zhakupov@halyk-kazteleport.kz",
    phone: "+7 (727) 244-11-15",
    startedAt: "2016-09-01",
    manager: "Жанар Ахметова",
    skills: ["Tier III", "Cooling", "BMS", "ИБП"],
    bio: "Руководит крупнейшим коммерческим ЦОД Алматы.",
    avatarTone: "#06805F",
  },
  {
    id: "e-003",
    fullName: "Асель Сейткали",
    position: "Директор по персоналу",
    department: "HR",
    city: "Алматы",
    email: "a.seitkali@halyk-kazteleport.kz",
    phone: "+7 (727) 244-11-08",
    tgUsername: "aselseitkali",
    startedAt: "2019-06-24",
    manager: "Айдын Сагинтаев",
    skills: ["T&D", "C&B", "HRBP", "Рекрутинг"],
    bio: "Строит команду компании. Запустила программу стажировок с КБТУ.",
    avatarTone: "#F9B101",
  },
  {
    id: "e-004",
    fullName: "Нурлан Оспанов",
    position: "Финансовый директор",
    department: "Финансы",
    city: "Алматы",
    email: "n.ospanov@halyk-kazteleport.kz",
    phone: "+7 (727) 244-11-04",
    startedAt: "2015-02-10",
    manager: "Айдын Сагинтаев",
    skills: ["IFRS", "Казначейство", "M&A"],
    bio: "20 лет в финансах банковского и телеком-секторов.",
    avatarTone: "#007A5C",
  },
  {
    id: "e-005",
    fullName: "Динара Муратова",
    position: "Руководитель B2B-продаж",
    department: "B2B-решения",
    city: "Астана",
    email: "d.muratova@halyk-kazteleport.kz",
    phone: "+7 (7172) 58-90-14",
    tgUsername: "din_muratova",
    startedAt: "2020-11-03",
    manager: "Айдын Сагинтаев",
    skills: ["Enterprise sales", "Cloud", "VPN/MPLS"],
    bio: "Ведёт ключевых клиентов из финансового сектора и госкорпораций.",
    avatarTone: "#F9B101",
  },
  {
    id: "e-006",
    fullName: "Бауыржан Калиев",
    position: "Главный инженер сети",
    department: "Сетевая инфраструктура",
    city: "Алматы",
    email: "b.kaliev@halyk-kazteleport.kz",
    phone: "+7 (727) 244-11-22",
    startedAt: "2012-04-18",
    manager: "Жанар Ахметова",
    skills: ["BGP", "MPLS", "DWDM", "Juniper", "Cisco"],
    bio: "Архитектор магистральной сети Halyk Kazteleport.",
    avatarTone: "#06805F",
  },
  {
    id: "e-007",
    fullName: "Айгуль Тлеубаева",
    position: "Руководитель ИБ",
    department: "Информационная безопасность",
    city: "Алматы",
    email: "a.tleubaeva@halyk-kazteleport.kz",
    phone: "+7 (727) 244-11-33",
    startedAt: "2021-01-14",
    manager: "Айдын Сагинтаев",
    skills: ["ISO 27001", "SOC", "PCI DSS", "NGFW"],
    bio: "Запустила корпоративный SOC 24/7. CISSP.",
    avatarTone: "#007A5C",
  },
  {
    id: "e-008",
    fullName: "Тимур Исмаилов",
    position: "Старший системный администратор",
    department: "Эксплуатация",
    city: "Шымкент",
    email: "t.ismailov@halyk-kazteleport.kz",
    phone: "+7 (7252) 50-44-18",
    startedAt: "2019-08-05",
    manager: "Жанар Ахметова",
    skills: ["Linux", "Kubernetes", "Ansible", "Zabbix"],
    bio: "Поддержка региональной инфраструктуры в южном регионе.",
    avatarTone: "#F9B101",
  },
  {
    id: "e-009",
    fullName: "Мадина Бекова",
    position: "Руководитель маркетинга",
    department: "Маркетинг и PR",
    city: "Алматы",
    email: "m.bekova@halyk-kazteleport.kz",
    phone: "+7 (727) 244-11-41",
    tgUsername: "madinabek",
    startedAt: "2022-05-02",
    manager: "Айдын Сагинтаев",
    skills: ["B2B маркетинг", "PR", "Event"],
    bio: "Курирует бренд Halyk Kazteleport и корпоративные события.",
    avatarTone: "#06805F",
  },
  {
    id: "e-010",
    fullName: "Ержан Сулейменов",
    position: "Начальник юридического департамента",
    department: "Юридический департамент",
    city: "Алматы",
    email: "e.suleimenov@halyk-kazteleport.kz",
    phone: "+7 (727) 244-11-09",
    startedAt: "2017-10-30",
    manager: "Айдын Сагинтаев",
    skills: ["Корпоративное право", "M&A", "Комплаенс"],
    bio: "Ведёт юридическое сопровождение сделок группы.",
    avatarTone: "#007A5C",
  },
  {
    id: "e-011",
    fullName: "Айгерим Омарова",
    position: "Менеджер B2B-продаж",
    department: "B2B-решения",
    city: "Атырау",
    email: "a.omarova@halyk-kazteleport.kz",
    phone: "+7 (7122) 45-66-80",
    startedAt: "2023-02-01",
    manager: "Динара Муратова",
    skills: ["Enterprise", "ТЭК"],
    bio: "Работает с клиентами нефтегазового сектора.",
    avatarTone: "#F9B101",
  },
  {
    id: "e-012",
    fullName: "Данияр Абишев",
    position: "DevOps-инженер",
    department: "Эксплуатация",
    city: "Алматы",
    email: "d.abishev@halyk-kazteleport.kz",
    phone: "+7 (727) 244-11-51",
    tgUsername: "daniyar_ab",
    startedAt: "2022-09-19",
    manager: "Тимур Исмаилов",
    skills: ["AWS", "Terraform", "GitLab CI", "Prometheus"],
    bio: "Автоматизация инфраструктуры облачной платформы Halyk Cloud.",
    avatarTone: "#06805F",
  },
];

export function getEmployee(id: string) {
  return employees.find((e) => e.id === id);
}
