import type { RequestItem } from "./types";

export const requests: RequestItem[] = [
  {
    id: "R-2641",
    type: "Отпуск",
    author: "Жанар Ахметова",
    department: "Эксплуатация",
    subject: "Ежегодный отпуск 14 дней",
    status: "На согласовании",
    submittedAt: "2026-04-21",
    dueAt: "2026-04-24",
    priority: "Средний",
  },
  {
    id: "R-2642",
    type: "IT-заявка",
    author: "Динара Муратова",
    department: "B2B-решения",
    subject: "Замена MacBook Pro 14 (M1 → M4)",
    status: "В работе",
    submittedAt: "2026-04-20",
    priority: "Низкий",
  },
  {
    id: "R-2643",
    type: "Доступ",
    author: "Данияр Абишев",
    department: "Эксплуатация",
    subject: "Доступ в prod-сегмент Halyk Cloud",
    status: "На согласовании",
    submittedAt: "2026-04-20",
    priority: "Высокий",
  },
  {
    id: "R-2644",
    type: "Командировка",
    author: "Динара Муратова",
    department: "B2B-решения",
    subject: "Астана, 05–07 мая, переговоры с КГД",
    status: "Одобрена",
    submittedAt: "2026-04-18",
    priority: "Средний",
  },
  {
    id: "R-2645",
    type: "Справка",
    author: "Тимур Исмаилов",
    department: "Эксплуатация",
    subject: "Справка 2-НДФЛ за 2025",
    status: "Выполнена",
    submittedAt: "2026-04-17",
    priority: "Низкий",
  },
  {
    id: "R-2646",
    type: "IT-заявка",
    author: "Мадина Бекова",
    department: "Маркетинг и PR",
    subject: "Установка Figma Enterprise на 6 рабочих мест",
    status: "Новая",
    submittedAt: "2026-04-22",
    priority: "Средний",
  },
  {
    id: "R-2647",
    type: "Отпуск",
    author: "Рустем Жакупов",
    department: "ЦОД",
    subject: "Учебный отпуск, 10 дней",
    status: "Одобрена",
    submittedAt: "2026-04-15",
    priority: "Низкий",
  },
  {
    id: "R-2648",
    type: "Доступ",
    author: "Айгерим Омарова",
    department: "B2B-решения",
    subject: "Доступ к CRM, роль Sales Lead",
    status: "В работе",
    submittedAt: "2026-04-19",
    priority: "Средний",
  },
];
